package com.example.sayli.fortifiedcards;

import android.content.Context;
import android.telephony.TelephonyManager;

import junit.framework.TestCase;


/**
 * Created by Aniiket on 2/15/2017.
 */
public class TestCScan extends TestCase {
    CScan cScan;
    // public TestCScan(){} //default constructor
    public void setUp() throws Exception {
        super.setUp();
        cScan=new CScan();


    }
    //checking if the IMEI number generated by the getCellId() function, is indeed the correct one!
    public void getIMEINumber(){
        //assertEquals checks if the second and the third parameters are equal, if not the message is displayed.
        assertEquals("The application is not capable " +
                "of reading the correct IMEI number of the device",cScan.getCellId(),cScan.telephonyManager.getDeviceId() );
    }



}